### ISSUE TITLE
Requests to reload the NLP inference must hit all the replicas

### ISSUE THREAD

**Issue by gcampax** [stanford-oval/almond-cloud#417]
In a replicated environment, there might be multiple independent NLP inference servers. The use case is to have 2, so updates can be made rolling with no downtime.
In this scenario, the training server needs to hit all replicas with reload commands, otherwise some server will keep serving the old model.

There can be two ways to implement this:
- the NLP inference server implement a leader election protocol; the admin requests hit the leader, which then forwards to the replicas
- the training server queries the list of active replicas and hits all of them
(note that if a replica dies, it will wake up with the updated model/dataset, so fault tolerance is preserved in either solution)

**Comment by gcampax** [comment]
@jgd5 this issue is preventing replication of the NLP server, which might be a scalability problem in the near future.
It's not just about reloading either: all three mutation endpoints (/admin/reload, /admin/reload-exact, /learn) need to be replicated.

Do you know of a good solution?

**Comment by jgd5** [comment]
As long the  replicates can reload simultaneously, it should be fairly straightforward. I can think of a few approaches: 

1. Using pubsub, e.g., aws SQS.  Each replica will subscribe to the same mutation topics.  The replica that receives the http request will broadcast a message to the mutation  topic.  All replicas will receive a message from the topic.

2. Using watcher, e.g. etcd watcher. Each replica will watch a specific key.  The replica that receives the http request will update the key .  All replicas will be notified when the key changes.

3. Store a centralized state (e.g., last reload timestamp) in db.  Each replica will periodically poll the db for sate changes.  The repilca that receives http request will update the state.

4. Get the endpoints from `kubectl get endpoints nlp` .  The replica that receives the http request will call each endpoint with a parameter that actually does the reload.

1 and 2 depend on external services. 3 requires polling the db. For 4, I'm not sure if k8s js client has the `get endpoints`  api otherwise, we might need to call `kubectl`.

**Comment by gcampax** [comment]
Mh, operationally, option 1 seems the most straight-forward. I am not worried about the external deps, given that this is only for replicated deployment.

**Comment by jgd5** [comment]
Sounds good.  I work on it this week.

**Comment by jgd5** [comment]
It turns we need to setup a separate SQS queue for each replica to support fanout scenario.  https://docs.aws.amazon.com/sns/latest/dg/sns-common-scenarios.html  
This means we need to manage the sqs queues as we bring up or shutdown a replica.  

I think the simplest solution now is option 1.  I just found we can use `listEndpointsForAllNamespaces` from https://raw.githubusercontent.com/kubernetes-client/javascript/master/src/gen/api/coreV1Api.ts to get the ip:port of all nlp replicas.
