### ISSUE TITLE
Question: Can almond-cloud be installed on Windows?

### ISSUE THREAD

**Issue by ecrofpu** [stanford-oval/almond-cloud#846]
Hello there, first of all I'd like to thank you for this package.

I was looking forward to installing almond-cloud locally, the thing is I own a Windows 10 machine. And the instructions assume Linux-like machine. I am stuck at [Step 3 - Configuration](https://github.com/stanford-oval/almond-cloud/blob/master/doc/installing-almond-cloud.md#step-3-configuration).

Can someone please tell me, is the `config.js` file auto-generated(if yes, how?). Also what could be the Windows 10 equivalent of `/etc/almond-cloud` path?

**Comment by gcampax** [comment]
almond-cloud can be installed on Windows if you use the docker image provided at https://hub.docker.com/r/stanfordoval/almond-cloud
Running natively on Windows is not possible. If you're interested in running Almond natively on Windows, you should check out [almond-server](https://github.com/stanford-oval/almond-server) instead.
If you use docker, it's recommended to use a container orchestrator, because you'll need to run multiple different services. You can find instructions for Kubernetes at <https://github.com/stanford-oval/almond-cloud/tree/master/k8s>. It's likely that it is possible to use docker-compose as well, but we don't have example configurations.

As for the config.js, it is not autogenerated. You need to write it yourself, taking https://github.com/stanford-oval/almond-cloud/blob/master/config.js as the starting point. You can also use JSON or YAML (with the appropriate file extension).
You only need to set the configuration keys that you wish to override.
