### ISSUE TITLE
Improve the UX of the voice input button

### ISSUE THREAD

**Issue by gcampax** [stanford-oval/almond-cloud#944]
Add a microphone or other indicator to make the function of the button more clear.

**Comment by gcampax** [comment]
I temporarily removed the voice button in #957, removing this from the blocker list.

**Comment by solyarisoftware** [comment]
Hi Giovanni,
I believe that's a good decision, for now.

A part e the the previous UX experience a bit misleading, I believe that managing speech input introduce issues.

I do not know anything about how you previously did the speech recognition processing (through the web client). 
- Maybe a Web Speech API (so using Google cloud service with lowest SLA)?
- Maybe any speech recognition cloud API? 
- Maybe any local ASR (DeepSpeech/Vosk/etc.)?

My point is that if accuracy of your ASR is not very good (WER>>10%), you are just introducing "noise" when monitoring your beta testing. The chat text interface avoid any speech misunderstanding due to the ASR quality.

BTW, just FYI I'm playing to interface Vosk and DeepSpeech offline ASR engines:
- https://github.com/solyarisoftware/voskJs
- https://github.com/solyarisoftware/deepspeechjs
 
Quality of my code is very questionable, it's just to give you an idea :)
 
cheers
giorgio

**Comment by almakantara** [comment]
Made a UI restyle of the icon, but didn't touch the behavior due to the fact that there was an unfinished discussion about it, if we get to a point on this topic, we can fix also the behavior then.
